### ISSUE TITLE
Build initial Watchtower Server

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/watchtower_server#1]
See https://app.skiff.com/file/cab5aed0-f072-4e18-9754-393e9937f498

The Watchtower Server is built using Rust and Axum. It plays a key role in log management and spotting potential issues in real-time. It consists of two main sections:

Services Interface: This part collects logs from different StarknetID services. it is gated by a jwt token, generated by a user (via a user jwt).

User Interface: This part lets users view logs. Like the services interface, it is also gated by a jwt token, generated via a password from the config.

The server works alongside a MongoDB database and a web app built with Next.js to keep StarknetID's systems running smoothly.

In the future, new features like automatic backups for databases could be nice.

https://github.com/starknet-id/quest_server can be used as inspiration for writing a HTTP server in rust

**Comment by fricoben** [comment]
Done
