### ISSUE TITLE
Fix watchtower db backup

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/watchtower_server#21]
Error
Error while saving db: 2023-11-01T08:57:35.598+0000 Failed: can't create session: failed to connect to mongodb://quests:REDACTED@149.202.84.229/?retryWrites=true&w=majority: connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.

**Comment by Marchand-Nicolas** [comment]
fixed in https://github.com/starknet-id/watchtower_server/pull/22
